from abc import ABC, abstractmethod
from typing import Dict, Any, Tuple
import numpy as np


class Layer(ABC):
    """Abstract neuron layer."""

    def __init__(self, name: str, N_neurons: int, config: Any):
        self.name = name
        self.N = N_neurons
        self.config = config

    @abstractmethod
    def get_equations(self) -> str:
        """Return Brian2 neuron model equations."""

    @abstractmethod
    def get_threshold(self) -> str:
        """Return spike threshold condition."""

    @abstractmethod
    def get_reset(self) -> str:
        """Return post-spike reset code."""

    def get_refractory(self):
        return 2  # ms, default

    def get_namespace(self, dt_ms: float) -> Dict[str, Any]:
        """Return Brian2 namespace dict for this layer's parameters."""
        return {}

    def get_initial_state(self) -> Dict[str, Any]:
        """Return initial variable values {name: value}."""
        return {}


class SynapseDefinition:
    """Holds all Brian2 synapse model code generated by a learning rule."""

    def __init__(self,
                 model: str,
                 on_pre: str,
                 on_post: str):
        self.model = model
        self.on_pre = on_pre
        self.on_post = on_post
