record:

  snapshot_interval_ms: 500

  groups:

    input:
      spike_raster:       true
      mean_firing_rate:   false
      membrane_potential: []
      membrane_potential_variables: []

    hidden:
      spike_raster:       true
      mean_firing_rate:   false
      membrane_potential: []
      membrane_potential_variables: []

  synapses:

    in->hid:
      weights_evolution:        []
      final_weights_per_sample: true


visualize:

  visualize_epoch: [0, 1]

  groups:

    input:
      spike_raster:       true
      mean_firing_rate:   false
      membrane_potential: []
      membrane_potential_variables: []

    hidden:
      spike_raster:       true
      mean_firing_rate:   false
      membrane_potential: []
      membrane_potential_variables: []

  synapses:

    in->hid:
      weights_evolution:        []
      final_weights_per_sample: true

  weights_per_neuron:
    in->hid:
      - 300
      - 400
